### ISSUE TITLE
Fetch elements in QueryAll sequentially

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/commercetools-sunrise-java#105]
Right now it is starting all the requests at once, we should try to fetch the next page once the previous has finished instead.

**Comment by butenkor** [comment]
What is the use case for sunrise shop to be able to fetch all the items at once?

**Comment by lauraluiz** [comment]
The use case was load all categories and product type, for example.

**Comment by lauraluiz** [comment]
This has been moved and re-implemented in the JVM SDK.
