### ISSUE TITLE
Enabling Gzip compression

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/commercetools-sunrise-java#229]
Maybe https://www.playframework.com/documentation/2.4.x/GzipEncoding

@schleichardt any other suggestion?

**Comment by schleichardt** [comment]
No, don't do that, please. It is just wasting precious Java memory, it should be a task of nginx or Apache Server but not of the JVM which garbage collects stuff.

**Comment by lauraluiz** [comment]
Let's talk about it once holidays are over.

**Comment by lauraluiz** [comment]
Already enabled in production

**Comment by schleichardt** [comment]
On nginx?

**Comment by hajoeichler** [comment]
Maybe by MaxCDN?

**Comment by lauraluiz** [comment]
Yes. For staging it is not enabled but it is for production, which is enough and the goal of this task.
