### ISSUE TITLE
Bug on checkout flow

### ISSUE THREAD

**Issue by lgiavedoni** [sphereio/commercetools-sunrise-java#278]
Validation error about lastNameShipping but that is undefined the form/post action. 

![screen shot 2016-02-01 at 3 38 24 pm](https://cloud.githubusercontent.com/assets/11629159/12730437/fc9de292-c8f9-11e5-8e5f-4fe219cd7cae.png)

**Comment by lauraluiz** [comment]
Handlebars Java version `4.0.3` seems to be generating this problem (the suffix value, passed as partial argument, is not always applied for some reason).

**Comment by lauraluiz** [comment]
Solved by a change in the template: https://github.com/sphereio/commercetools-sunrise-design/pull/362
