### ISSUE TITLE
convert to activator template

### ISSUE THREAD

**Issue by schleichardt** [sphereio/commercetools-sunrise-java#33]

**Comment by lauraluiz** [comment]
@schleichardt is it still valid?

**Comment by schleichardt** [comment]
Yep, we should do this soon.

**Comment by schleichardt** [comment]
how to do it: https://www.lightbend.com/activator/template/contribute

**Comment by schleichardt** [comment]
it is live: https://www.lightbend.com/activator/templates#filter:commercetools

**Comment by lauraluiz** [comment]
Yay!

**Comment by lauraluiz** [comment]
@schleichardt can you add some docu about how to use it or a link to some external documentation? Nothing that requires work, but something that doesn't make us forget about that :)

**Comment by schleichardt** [comment]
sure:

1. download activator at http://www.lightbend.com/activator/download (better download the mini-package)
1. `activator new my-project-name commercetools-sunrise-java`
1. `cd my-project-name`
