### ISSUE TITLE
http should be redirected to https

### ISSUE THREAD

**Issue by trangng** [sphereio/commercetools-sunrise-java#364]
http pages should all be redirected to their https version. we decided to have the shop only in https since it has a positive influence on seo ranking. 

http://sunrise.commercetools.com/en/home --> https://sunrise.commercetools.com/en/home

for now both are working and creating duplicate content

**Comment by hajoeichler** [comment]
Please use demo.commercetools.com in general

**Comment by schleichardt** [comment]
Isn't this a hosting/ops configuration thing instead of a Java programming task?

**Comment by hajoeichler** [comment]
Originally this was done by our LB, but with MaxCDN in front - the connection between MaxCDN and LB is always using https. So it must be handled in the application or in MaxCDN.

**Comment by lauraluiz** [comment]
I would rather leave the app clean from that, I don't think it's the place to decide this kind of stuff. The more we enforce, the more restrictions we create and the less flexible Sunrise is.
Let's go with the MaxCDN approach for our hosted demo.

**Comment by hajoeichler** [comment]
We might can implement this as EdgeRule in MaxCDN.

**Comment by hajoeichler** [comment]
https://www.maxcdn.com/one/tutorial/edge-rules-recipes/#force_ssl

Currently I get an error when I try to set this. I will try further.

**Comment by hajoeichler** [comment]
Fixed now ;)

**Comment by lauraluiz** [comment]
Thanks! :)
