### ISSUE TITLE
SBT heroku

### ISSUE THREAD

**Issue by schleichardt** [sphereio/commercetools-sunrise-java#60]
@lauraluiz Do we need something like this https://github.com/heroku/sbt-heroku?

@mmoelli mentioned it.
I think for our travis builds we are already deploying an artifact and do not let heroku build it again.

**Comment by lauraluiz** [comment]
@schleichardt are we currently avoiding Heroku to build the artefact again or do you mean that would be achieved with sbt-heroku?

**Comment by schleichardt** [comment]
Yes, the idea is to improve the speed of the heroku deployment. That would be achieved with the plugin, I hope.

**Comment by lauraluiz** [comment]
That sounds great. So if that's the case, let's try it.

**Comment by lauraluiz** [comment]
This unfortunately is not compatible with the Heroku button. We could implement it only for Sunrise deployment to staging to improve the speed, but then we cannot guarantee the button works. As the latter is more important right now, let's leave this for now.
